import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import FireIcon from '@/components/icons/FireIcon';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body
        className={
          inter.className +
          ' bg-gradient-to-b from-bg-gradient-from to-bg-gradient-to min-h-screen text-white'
        }
      >
        <main className='p-4 max-w-4xl mx-auto'>
          <header className='flex justify-between my-8'>
            <Link href='/' className='flex gap-1'>
              <FireIcon />
              <span>Awesome Captions</span>
            </Link>
            <nav className='flex gap-6 text-white/80'>
              <Link href='/'>Home</Link>
              <Link href='/pricing'>Pricing</Link>
              <a href='mailto:contact@awesomecaptions.com'>Contact</a>
            </nav>
          </header>
          {children}
        </main>
      </body>
    </html>
  );
}
